;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ac-haskell-process-popup-doc
	coffee-dedent-line-backspace
	comment-dwim
	cua-cancel
	cua-paste
	dired-do-copy
	dired-do-shell-command
	electric-newline-and-maybe-indent
	emmet-expand-line
	emmet-wrap-with-markup
	ergoemacs-copy-line-or-region
	ergoemacs-cut-line-or-region
	ergoemacs-forward-block
	ergoemacs-previous-user-buffer
	ergoemacs-select-current-line
	ergoemacs-shortcut
	ergoemacs-toggle-letter-case
	ghc-goto-next-hole
	helm-imenu
	jinja2-insert-var
	keyboard-quit
	kill-region
	mark-whole-buffer
	mouse-minor-mode-menu
	org-beginning-of-line
	org-end-of-line
	org-self-insert-command
	python-indent-electric-colon
	sgml-slash
	sp--self-insert-command
	sp-remove-active-pair-overlay
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	comint-previous-input
	delete-window
	dired-jump
	dired-maybe-insert-subdir
	diredp-find-file-reuse-dir-buffer
	diredp-next-line
	diredp-previous-line
	end-of-buffer
	ergoemacs-next-user-buffer
	ergoemacs-read-key-default
	ergoemacs-select-current-block
	helm-buffers-list
	helm-find-files
	ido-switch-buffer
	ignore
	js2-mode-show-node
	keyboard-escape-quit
	mouse-buffer-menu
	mouse-set-secondary
	python-shell-send-buffer
	revert-buffer
	smex
	tern-ac-dot-complete
	undefined
	view-emacs-problems
	))
