;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		coffee-dedent-line-backspace
		comment-dwim
		dired-do-copy
		dired-do-shell-command
		emmet-expand-line
		emmet-wrap-with-markup
		ergoemacs-copy-line-or-region
		ergoemacs-forward-block
		ergoemacs-previous-user-buffer
		ergoemacs-select-current-line
		ergoemacs-shortcut
		ergoemacs-toggle-letter-case
		helm-imenu
		jinja2-insert-var
		keyboard-quit
		kill-region
		mark-whole-buffer
		mouse-minor-mode-menu
		org-beginning-of-line
		org-end-of-line
		org-self-insert-command
		python-indent-electric-colon
		sgml-slash
		sp--self-insert-command
		sp-remove-active-pair-overlay
		yas-expand
		))

(setq mc/cmds-to-run-once
      '(
		comint-previous-input
		delete-window
		dired-jump
		dired-maybe-insert-subdir
		diredp-find-file-reuse-dir-buffer
		diredp-next-line
		diredp-previous-line
		end-of-buffer
		ergoemacs-next-user-buffer
		ergoemacs-read-key-default
		ergoemacs-select-current-block
		helm-find-files
		ido-switch-buffer
		ignore
		js2-mode-show-node
		mouse-buffer-menu
		mouse-set-secondary
		python-shell-send-buffer
		revert-buffer
		smex
		tern-ac-dot-complete
		view-emacs-problems
		))
